# Build and publish the .NET project to GitHub Packages
name: Publish to GitHub Packages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0
      - name: Authenticate with GitHub Packages
        run: |
          dotnet nuget add source \
            --username tommcdo \
            --password "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}" \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/TheLittlestPinecone/index.json"
      - name: Publish Pinecone.Events
        uses: ./.github/actions/publish-dotnet-package
        with:
          package: Pinecone.Events
          access-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Publish Pinecone.EventPublisher
        uses: ./.github/actions/publish-dotnet-package
        with:
          package: Pinecone.EventPublisher
          access-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Publish Pinecone.EventSubscriber
        uses: ./.github/actions/publish-dotnet-package
        with:
          package: Pinecone.EventSubscriber
          access-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
